# -*- coding: utf-8 -*-
INSTALLED_ADDONS = [
    'aldryn-django',
    'aldryn-cms',
    # <INSTALLED_ADDONS>
    # Warning: this is auto-generated by aldryn
    # </INSTALLED_ADDONS>
    # 'aldryn-newsblog',
    # 'aldryn-people',
]

import aldryn_addons.settings
aldryn_addons.settings.load(locals())


INSTALLED_APPS.extend([
    # add you project specific apps here
])

TEMPLATE_CONTEXT_PROCESSORS.extend([
    # add you project specific template context processors here
])

MIDDLEWARE_CLASSES.extend([
    # add you project specific middlewares here
])
