# -*- coding: utf-8 -*-

# TODO: for parsing ease, those settings generated by CP should probably go into a generated_settings.json. Or be enclosed with some sort of markup
ALDRYN_BOILERPLATE_NAME = 'legacy'
INSTALLED_ADDONS = [
    'aldryn-django',
    'aldryn-cms',
    # <INSTALLED_ADDONS>
    # Warning: this is auto-generated by aldryn
    # </INSTALLED_ADDONS>
    # 'aldryn-newsblog',
    # 'aldryn-people',
]


import aldryn_addons.settings
aldryn_addons.settings.load(locals())


# INSTALLED_APPS.extend([
#     # add you project specific apps here
#     'myapp',
# ])
#
# TEMPLATE_CONTEXT_PROCESSORS.extend([
#     # add you project specific template context processors here
# ])
#
# MIDDLEWARE_CLASSES.extend([
#     # add you project specific middlewares here
# ])
